### ISSUE TITLE
Error with using /usr/lib/python2.7/httplib.py

### ISSUE THREAD

**Issue by ipeacocks** [ashokrajar/SOLR-Nagios-Check-Plugin#5]
Hello!

Is it bug in code or my fault?

``` bash
./check_solr.py -u http://localhost:8090/solr -w 70 -c 99

Traceback (most recent call last):
  File "./check_solr.py", line 82, in <module>
    solr_doc_stats = CollectStat('CORE', 'searcher')
  File "./check_solr.py", line 46, in __init__
    doc = ET.fromstring(urllib.urlopen(cmd_options.solr_url + "/admin/stats.jsp").read())
  File "/usr/lib/python2.7/urllib.py", line 86, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 207, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 344, in open_http
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 958, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 818, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 780, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 761, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
IOError: [Errno socket error] [Errno 111] Connection refused
```

Thank you!

**Comment by ipeacocks** [comment]
Sorry it was my fault. Was wrong link.

But script still sometimes shows errors on non-staandart options.
